### PR TITLE
#1401. [Patterns] cast, null-assert and null-check patterns tests added

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Comment by sgrekhov** [comment]
@chloestefantsova please review

**Review by eernstg — APPROVED** [review]
LGTM

**Comment by eernstg** [comment]
@chloestefantsova, I'm afraid the behavior of github just confused me: I looked at this PR using a link from the email, but it only showed me changes from 1 commit, and that was a typo fix. So I thought it was a tiny thing and LGTM'd it.

However, I can see that it is quite long when showing changes from all commits. I hope it's OK if you take over and look at it?

**Comment by sgrekhov** [comment]
@chloestefantsova please review

**Comment by sgrekhov** [comment]
@chloestefantsova please review

**Review by eernstg — APPROVED** [review]
LGTM

**Pull request merged**
