### PR TITLE
Fixes #1797. Expect compile-time error in case of nullable Struct member

### LINKED ISSUE #1797: Disallow nullable struct fields
co19/LibTest/ffi/Struct/Struct_A03_t02 should be updated to check for compile-time errors on `?` struct fields.

See:

* https://github.com/dart-lang/sdk/issues/51041

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by dcharkes — APPROVED** [review]
lgtm

Thanks @sgrekhov !

Please note that I had to revert the change temporarily:

* https://github.com/flutter/flutter/issues/120260

So if you build the latest Dart, this test will fail again.

I will reland the errors on nullable fields when the Flutter dependency has been rolled.

**Comment by eernstg** [comment]
Looks like this one is ready to land. @dcharkes, do we need to wait for a revert-revert?

**Comment by dcharkes** [comment]
> Looks like this one is ready to land. @dcharkes, do we need to wait for a revert-revert?

Revert-revert would be less approvals, but I don't mind either way.

**Comment by eernstg** [comment]
OK, then I'll land this one. Thanks!

**Review by eernstg — APPROVED** [review]
LGTM

**Pull request merged**
