### PR TITLE
Fixes #2046. `records`, `patterns`, `class-modifiers` experimental flags removed

### LINKED ISSUE #2046: Remove experiment flags for 3.0 features
Experiments to remove:
```
sealed-class
class-modifiers
records
patterns
```

/cc @eernstg

### PR DESCRIPTION
**Pull request by sgrekhov**
This PR contains 1,904 changed files with 1 addition and 3,791 deletions. The only addition is

```
diff --git a/LanguageFeatures/Records/type_promotion_A02_t01.dart b/LanguageFeatures/Records/type_promotion_A02_t01.dart
index 6c21f8adcd..d48909f58a 100644
--- a/LanguageFeatures/Records/type_promotion_A02_t01.dart
+++ b/LanguageFeatures/Records/type_promotion_A02_t01.dart
@@ -9,7 +9,7 @@
 /// @description Checks private fields promotion for records.
 /// @author sgrekhov22@gmail.com

-// SharedOptions=--enable-experiment=records,inference-update-2
+// SharedOptions=--enable-experiment=inference-update-2
```

### CODE REVIEW

**Comment by eernstg** [comment]
Oh, just one thing: How do we know that this isn't too early?

**Comment by athomas** [comment]
experimental_features.yaml says they were enabled in 3.0.

**Comment by eernstg** [comment]
OK, I just didn't think it was a given that no bot will run with an older configuration, starting at some point in time <= now. ;-)

**Comment by athomas** [comment]
> OK, I just didn't think it was a given that no bot will run with an older configuration, starting at some point in time <= now. ;-)

Because co19 is pinned, they would also use an older co19 version that still has the flags. So I think we're good.

**Review by athomas — APPROVED** [review]

**Review by eernstg — APPROVED** [review]
`gh pr checkout 2047` and `grep` can do a lot of work when we have 1904 files changed. ;-)
LGTM.

**Pull request merged**
