### PR TITLE
Fixes #1372. Expected error message text fixed

### LINKED ISSUE #1372: Failures on [co19] Roll co19 to 14c158a94ae9ce9420bd612fdc089602c6d6b3bd
There are new test failures on [[co19] Roll co19 to 14c158a94ae9ce9420bd612fdc089602c6d6b3bd](https://dart-review.googlesource.com/c/sdk/+/252425).

The tests
```
co19/LanguageFeatures/Horizontal-inference/horizontal_inference_t07 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Horizontal-inference/horizontal_inference_t07 MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
```

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by eernstg — APPROVED** [review]
LGTM!

**Comment by eernstg** [comment]
A similar PR is upcoming for the pre-nnbd branch?

**Comment by sgrekhov** [comment]
@eernstg Hmm. No. Does Horizontal inference feature affect `pre-nnbd` as well? If so I'll add these tests to `pre-nnbd` branch.

**Comment by eernstg** [comment]
Oh, maybe I just misremember, but I thought that I saw a failure on both branches about this extra period on the error message, and I didn't notice that there was a connection to horizontal inference. Let me try to find the failure log...

**Comment by eernstg** [comment]
I think it must have been a completely different test, this one is in the `Horizontal-inference` directory (and I did not see that, I just thought I could remember that I saw this "period failure" twice ;-).

**Comment by eernstg** [comment]
OK, the log is [here](https://github.com/dart-lang/co19/issues/1372#issuecomment-1192653404), I was just misremembering the situation. So we're done, thanks!

**Pull request merged**
