### PR TITLE
#673. IFrame tests that don't actually test IFrame removed

### PR DESCRIPTION
**Pull request by sgrekhov**
When investigatint #673 found that these two test have nothing to do with `IFrame` and can be safely removed. Seems that these tests are result of copy-paste from `Element`

### CODE REVIEW

**Comment by eernstg** [comment]
@zanderso, I do not know the detailed workings of 'dart:http', so it would be great if you can take a look at this PR.

**Comment by sgrekhov** [comment]
Ups. I committed findProxy tests in a wrong branch. I'll fix it.

**Comment by eernstg** [comment]
Aha, thanks!

@zanderso, this means that there's no need to ask for your input on this PR after all!

**Comment by sgrekhov** [comment]
@eernstg fixed. Sorry for mistake

**Review by eernstg — APPROVED** [review]
LGTM!

**Pull request merged**
