### PR TITLE
#2349. Add more tests for constant constructors of the extension types

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by eernstg — COMMENTED** [review]
Looks good, just a couple of typos (and one comment about the things being tested, with no requests about changing anything, just reflecting the fact that I was slightly puzzled by the code ;-).

**Comment by sgrekhov** [comment]
Typos fixed. Please review

**Comment by sgrekhov** [comment]
@sgrekhov @chloestefantsova friendly ping

**Review by eernstg — APPROVED** [review]
LGTM

**Comment by sgrekhov** [comment]
Thank you!

**Pull request merged**
