### PR TITLE
#2094. Move and rename mixin tests to follow the current spec structure

### PR DESCRIPTION
**Pull request by sgrekhov**
`co19/Language/Mixins/*` tests are all green on all configurations. So, we agreed with @athomas that it is safe to rename such tests

### CODE REVIEW

**Comment by eernstg** [comment]
Moved `syntax_t26.dart` to `syntax_t11.dart`, `syntax_t27.dart` to `syntax_t12.dart`, changes a couple of import URIs from double quote to single quote format. All other changes are shown correctly as renames in the github 'files changed' UI.

**Review by eernstg — APPROVED** [review]
LGTM

**Review by eernstg — COMMENTED** [review]
Oops, one more change needed: deferred_t02.dart and deferred_t03.dart have a mixin application class declaration (the kind that uses `=`) with a class body (like `class C = A with M {}`). We should change that such that the reported compile-time error has the correct fault to complain about.

**Comment by sgrekhov** [comment]
Thank you for noticing! Fixed

**Review by eernstg — APPROVED** [review]
Thanks! LGTM

**Review by eernstg — COMMENTED** [review]
Oops, one more thing: `deferred_t01.dart` was changed, too, and there was no syntax error in that one (that's not a mixin application class). I think that one should just be changed back to have `{}`.

**Comment by sgrekhov** [comment]
Really. Sorry. Reverted

**Review by eernstg — APPROVED** [review]
No problem, LGTM!

**Pull request merged**
