### PR TITLE
#2559. Add augmented expression tests

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by eernstg — APPROVED** [review]
Good catch, I hadn't thought about several of those cases!

LGTM.

**Review by eernstg — COMMENTED** [review]
There was a handful of syntax errors after all: An `augment extension` cannot have an `on` clause.

**Comment by sgrekhov** [comment]
> An augment extension cannot have an on clause.

Forgot about it. Thank you for noticing! Fixed.

**Review by eernstg — APPROVED** [review]
LGTM

**Pull request merged**
