### PR TITLE
Fixes #1613. Fixed wrong use of relational operators

### LINKED ISSUE #1613: Some of the pattern tests expect a record element to understand the `>` operation
Some of the tests use the `>` operation in a sub-pattern of a record pattern. However, nothing is known about the type of the corresponding element of the record, and the compiler can't produce the code applying `>` to a receiver of the `Object` type.

Examples of the described expectations are the following:

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/record_A01_t05.dart#L47

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/record_A01_t06.dart#L46

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by chloestefantsova — APPROVED** [review]

**Comment by sgrekhov** [comment]
@chloestefantsova please let me know if we need a new roll of co19 tests to enable these recent fixes

**Comment by chloestefantsova** [comment]
I think it could be helpful. The updated tests may reveal new issues in the implementation that I will need to work on.

**Comment by sgrekhov** [comment]
@chloestefantsova please review https://dart-review.googlesource.com/c/sdk/+/277520

**Comment by chloestefantsova** [comment]
Done. Thanks!

**Pull request merged**
