### PR TITLE
#2559. Fix extension types syntax

### PR DESCRIPTION
**Pull request by sgrekhov**
The next roll should have a lot of new failures  :)

### CODE REVIEW

**Review by eernstg — APPROVED** [review]
LGTM

**Comment by eernstg** [comment]
Oh, there was one typo in LanguageFeatures/Augmentation-libraries/augmenting_setters_A01_t01.dart after all.

**Comment by sgrekhov** [comment]
Really. Thank you for noticing! Fixed.

**Review by eernstg — APPROVED** [review]
LGTM

**Pull request merged**
