### PR TITLE
#2142. Move static analysis member invocation tests to Extension types dir

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by eernstg — APPROVED** [review]
LGTM

**Comment by eernstg** [comment]
Oops, just noticed that static_analysis_member_invocation_A05_t03.dart has two syntax errors: `extension types`.

**Comment by sgrekhov** [comment]
Indeed. Thank you. Fixed

**Comment by eernstg** [comment]
Thanks!

**Pull request merged**
