### PR TITLE
Remove extra space

### PR DESCRIPTION
**Pull request by asashour**
This PR does two things:

1. Remove extra space in various places in text.
2. Change `a` to `an` in `LibTest/collection/UnmodifiableMapView/UnmodifiableMapView_A01_t01.dart`.

### CODE REVIEW

**Review by eernstg — COMMENTED** [review]
OK, just noticed a couple of things:

There are some occurrences of ` ,` (space comma), they should probably be changed similarly. Also, the change to async_utils.dart looks like an unintended undo to a recent update (where usages of `Function.apply` are changed to use other features wherever possible, because Dart-to-WASM does not yet support `Function.apply`).

**Comment by asashour** [comment]
- space after comma was changed.


> ... the change to async_utils.dart looks like an unintended undo ...

I am afraid I couldn't find any change to `async_utils.dart`

**Comment by eernstg** [comment]
> I am afraid I couldn't find any change to `async_utils.dart`

My bad! I compared to `master` rather than `master...`, and there was just one commit extra.

**Review by eernstg — APPROVED** [review]

**Comment by eernstg** [comment]
Thanks!

**Pull request merged**
