### PR TITLE
Make sure we expect type exception in checked mode.

### PR DESCRIPTION
**Pull request by aam**
Hopefully this addresses https://github.com/dart-lang/sdk/issues/30667.

### CODE REVIEW

**Comment by sgrekhov** [comment]
@aam, mentioned tests work well in Dart now (both checked and production modes). With this PR applied they fail on Dart in checked mode (becaust there is no Type error). I'm not familiar with the dartk, should all dart tests work in the same way in dartk? May be it makes sense simply swich off these tests in a .status file? Please, also note, that there is strong-mode branch, containing co19 tests, adapted for strong mode. May be it makes sense to use this branch for dartk testing?

**Comment by aam** [comment]
I believe Dart VM is incorrect in not throwing type check errors in those tests in checked mode.

@crelier , what do you think?

**Comment by crelier** [comment]
@aam, the spec does not say anything about the runtime type of the literal async function or what behavior is expected when assigning an async function. The VM uses dynamic (always) as the return type, and that is the reason we do not get a type error. Remember also that the VM does not (yet) implement strong mode and using dynamic as bottom is not yet an issue.

However, the spec states that the static type of the literal async function has a return type of Future< flatten(T0) >, where T0 in the first test is int (if you apply type inference). Without type inference or the analyzer magic, the VM cannot tell what is T0. We could use Future instead of dynamic as return type, which would throw a type error in the first test. But this becomes an issue again when implementing strong mode, unless we use Future<Null>.

This is an interesting question and I do not have a clear answer. My guts feeling tells me this is indeed a bug. I think the current VM behavior is fine and does not represent a problem in practice, but I could be convinced otherwise, especially in the light of strong mode.

**Comment by aam** [comment]
Yeah, I think the intent is to use `Future`, `Stream`, `Iterable` instead of `dynamic`. At least that is what dartk (and dart2js I assume) do - below is how those tests are flagged by Frontend.

```
FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_form_3_asyncs_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(int, {bool p2}) => Stream' is not a subtype of type '(int, {bool p2}) => Future' of 'sfp1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_asyncs_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_asyncs_t03.dart
Took 0:00:00.840386

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_form_3_asyncs_t03


FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_form_3_async_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(int, {int p2}) => Future' is not a subtype of type '(int, {int p2}) => int' of 'ff1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_async_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_async_t03.dart
Took 0:00:00.930430

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_form_3_async_t03


FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_dynamic_async_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(int, [int]) => Future' is not a subtype of type '(int, [int]) => int' of 'ffp1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_async_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_async_t03.dart
Took 0:00:00.884661

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_dynamic_async_t03


FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_dynamic_asyncs_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(int, [bool]) => Stream' is not a subtype of type '(int, [bool]) => Future' of 'sfp1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_asyncs_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_asyncs_t03.dart
Took 0:00:00.875539

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_dynamic_asyncs_t03


FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_dynamic_syncs_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(int, [List]) => Iterable' is not a subtype of type '(int, [List]) => Future' of 'ifp1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_syncs_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_dynamic_syncs_t03.dart
Took 0:00:00.737978

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_dynamic_syncs_t03


FAILED: dartk-vm-checked release_x64 co19/Language/Expressions/Function_Expressions/static_type_form_3_syncs_t03
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
type '(List, {List p2}) => Iterable' is not a subtype of type '(List, {List p2}) => Future' of 'ifp1'
#0      main (file:///sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_syncs_t03.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate:1242:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/ReleaseX64/patched_sdk --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/dart-sdk/sdk/.packages /dart-sdk/sdk/tests/co19/src/Language/Expressions/Function_Expressions/static_type_form_3_syncs_t03.dart
Took 0:00:00.877401

Short reproduction command (experimental):
    python tools/test.py -m release -c dartk --checked co19/Language/Expressions/Function_Expressions/static_type_form_3_syncs_t03
```

**Comment by sgrekhov** [comment]
Yes, these tests fail on dart2js in a checked mode as well. We have different behaviour of VM and dart2js/dartk and it's unclear which one is correct. I've created SDK issue for that dart-lang/sdk#30813

**Comment by sgrekhov** [comment]
According to https://github.com/dart-lang/sdk/issues/30813#issuecomment-330753284 both VM and dartk are correct. AFAIU the plan is to use tests from this branch for Dart 1.x testing and tests from strong-mode branch for Dart 2.0. In a strong-mode we are expecting an error in these tests. If so, @aam, please, for now, simply switch off these tests in a sdk\tests\co19\co19-kernel.status file as it is done for these tests in sdk\tests\co19\co19-dart2js.status. When strong-mode branch became a main branch for Dart tests then this issue will re addressed.

**Pull request closed without merging**
