### PR TITLE
#2559. Add more test cases for augmented expression

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Review by eernstg — COMMENTED** [review]
Looks good!

A couple of terminology issues came up, it would be nice to think a little bit about them. In particular, the terminology around records is currently not in a very good shape.

**Review by eernstg — APPROVED** [review]
LGTM!

**Comment by sgrekhov** [comment]
Thank you! Descriptions updated. PTAL

**Comment by eernstg** [comment]
(-:  .backwards go to appears time the situations some In

**Pull request merged**
