### PR TITLE
Fixes #1526. [Records] Expect error for field names that start with underscore

### LINKED ISSUE #1526: LanguageFeatures/Records/record_type_annotations_A06_t02
https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#record-expressions:

> It is a compile-time error if a record has any of:
> ...
> A field name that starts with an underscore.

The same rule applies to record types https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#record-type-annotations:

> It is a compile-time error if a record type has any of:
> ...
> A field name that starts with an underscore.

`LanguageFeatures/Records/record_type_annotations_A06_t02` test checks that this is allowed for positional fields, but in the current version of the spec there are no exceptions for names of positional fields. So this test needs to be updated.

https://github.com/dart-lang/co19/blob/642b786a850a9de5ab75ce872c98d7d560fe9fc2/LanguageFeatures/Records/record_type_annotations_A06_t02.dart#L33-L50

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Comment by sgrekhov** [comment]
@chloestefantsova please review

**Comment by sgrekhov** [comment]
@chloestefantsova please review

**Review by alexmarkov — APPROVED** [review]
lgtm

**Comment by sgrekhov** [comment]
@eernstg this PR was approved, please merge it

**Pull request merged**
